### ISSUE TITLE
Frequencies turning off randomly

### ISSUE THREAD

**Issue by capzDE** [pierr3/TrackAudio#182]
Since a couple of days I am experiencing a very odd issue where all frequencies set to TX suddenly become unselected (i.e. TX, RX, and XCA are off) without any input from my side. I have attached the [log](https://github.com/user-attachments/files/17530414/trackaudio.log) from yesterday evening's session where I experienced the issue at least once pretty much right at the beginning (within the first 10-15 minutes or so); unfortunately, I didn't spot anything that might indicate a reason as to why this was happening.
Other frequencies that I have set to just RX with SPK activated don't appear to be affected as far as the green buttons in the client are concerned, though it occasionally seems as though chatter is taking place on these frequencies that is not being output by the speaker when it was working before.

I first experienced this issue with 1.3.0b1 (though not from the get-go); updating to 1.3.0b2 did not resolve the issue

**Comment by pierr3** [comment]
Do the buttons unselect in the UI as well?

**Comment by capzDE** [comment]
> Do the buttons unselect in the UI as well?
Yes, the buttons also unselect in the UI. As soon as I notice the issue, I can also simply press them again to activate TX, RX, and XC(A) and it will work again, but the issue often reoccurs after a bit.

**Comment by pierr3** [comment]
Any chance your PTT is F5?

**Comment by capzDE** [comment]
> Any chance your PTT is F5?

Nope, it's actually not a default keyboard input at all but comes from a USB controller (in the TrackAudio settings, it's called "Arduino Leonardo 1", hardwarewise it's just the physical PTT button on my handheld mic); and I don't believe I'm pressing F5 at all during controlling, but I'll keep an eye on it (only thing I can imagine is that maybe I sometimes accidentally graze F5 and it registers as an input when I press F6, which is the Euroscope shortcut for opening the flight data strip).

**Comment by pierr3** [comment]
Ok thanks, please have a look if by any chance you'd be pressing F5 when TrackAudio is in focus, and I'll also add a failsafe against that.

**Comment by jannikvogel** [comment]
had the same issue, also using a USB controller as PTT. sadly no log available

**Comment by Ismailhassan12** [comment]
Same here.

**Comment by capzDE** [comment]
Seeing as I'm apparently not the only one experiencing this issue, I just want to put out a few observations I've made since opening this issue in the hopes that it helps narrow down the list of possible causes:

- the issue persists in 1.3.0b3
- the track audio window was never in focus when the issue occurred and in most instances, it wasn't even shown on any screen (i.e. either hidden behind other windows or minimized to the taskbar)
- I'm fairly certain that I didn't press F5 coincidingly with the issue
- it doesn't appear to matter whether I am XCA on multiple frequencies, RX without TX on other frequencies going to my speaker, or only using a singular frequency without any other frequencies crosscoupled or monitored (however, it seems that in most, if not all, cases all frequencies set to TX/XCA turn off)

**Comment by capzDE** [comment]
Another thing I noticed yesterday when testing around with some audio settings: I turned off SPK for another frequency (which was set to RX only) which resulted in an error message (can't fully reconstruct it from memory, but it ended in OnSPK" and was just one line - I'll try to get a screengrab if I see it again) and simultaneously my primary frequency (set to RX/TX and XCA) switched off completely. However, this is different from other occurrences of the issue in that it followed me actively changing something while normally the issue occured randomly without input besides pressing the PTT, but could still be related.

**Comment by pierr3** [comment]
This should also have been fixed in beta 4 - let us know if not

**Comment by capzDE** [comment]
I'm unfortunately still experiencing the issue very regularly, with the most recent occurrence right at the beginning of yesterday's session (05 Dec 2024, beginning shortly before 2000LT). I have attached the logs (with verbose logging enabled, if I did it correctly); maybe you can find something of relevance in it.

[trackaudio.log](https://github.com/user-attachments/files/18040480/trackaudio.log)
[trackaudio-afv.log](https://github.com/user-attachments/files/18040482/trackaudio-afv.log)

**Comment by beardedtoad** [comment]
Same issue here - happens randomly after 40-60 minutes, number of active frequencies/xca doesn't seem to matter. Will attach logs once I figure out how to enable them.

**Comment by FritzATC** [comment]
Same issue here . . starts after ~3 minutes . . and repeats. Windows 11. No USB PTT.

**Comment by GeorgeBarlow** [comment]
> Same issue here . . starts after ~3 minutes . . and repeats. Windows 11. No USB PTT.

Can you state the time it happened (roughly) and provide your log file

**Comment by FritzATC** [comment]
See email ;-)

**Comment by FritzATC** [comment]
to add: whole day today, several long sessions (@ 2 different stations), 
no interruptions at all!

only change: new install yesterday evening

sooo . . seems solved one way or another . .

tnx for your time!

**Comment by GeorgeBarlow** [comment]
Sorry I didn't see your other messages, only saw them through the quote trail on your most recent message, I can't also see any attached log file (it is most likely GitHub doing something strange)

My initial thoughts are that this issue could be related to incorrectly detecting AFV voice timeouts though, of course, I need to do more research to be certain.

I'm glad it works again. Let us know if it happens again. If you get time to reply to this, can you try attaching the log file and note the timestamp of roughly when it previously occurred for a trail in this issue? The more data we have, the more we can try to connect the dots in case the problem comes back. 

I'm really glad though that you're enjoying the client, have a good evening!

**Comment by kodiakastu** [comment]
Hello, 
chiming in with the same issue. And I'm not able to correlate that "soft disconnect" with anything else going on. 

I listen frequently to other stations. I now use the local ATIS as a canary. When the event happen, I try to start back all the RXs. Only my station is unselected. So to listen again to other station I try to unselect/select the RX but I receive message "[0000z] Invalid action on invalid Radio. RX.". (sorry if it sounds wrong English is not my first language).

Let me know where the relevant log files are and I'll provide them with pleasure!

1.3.0-beta.5

**Comment by GeorgeBarlow** [comment]
Can you enable verbose logging and provide the new log file (instructions as per README) and try to get this issue to show again?

**Comment by kodiakastu** [comment]
Hello,

This is my first drop of the night. Do you want more ?

[log1.log](https://github.com/user-attachments/files/18700140/log1.log)

**Comment by capzDE** [comment]
Just wanted to quickly chime in and say that I have not experienced the issue anymore in the last couple of weeks; using 1.3.0b5.

**Comment by FritzATC** [comment]
Me too! All fine now!
Greetz,
Fritz

**Comment by pierr3** [comment]
Great to hear! I had this happen a while back but it was because my connection dropped. Hopefully the current fixes will hold!

**Comment by pierr3** [comment]
Closing, feel free to re-open if it occurs
